/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type { Dummy, DummyInterface } from "../Dummy";

const _abi = [
  "function data() view returns (bytes)",
  "function set(bytes)",
] as const;

export class Dummy__factory {
  static readonly abi = _abi;
  static createInterface(): DummyInterface {
    return new Interface(_abi) as DummyInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): Dummy {
    return new Contract(address, _abi, runner) as unknown as Dummy;
  }
}
