/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  ERC1967UpgradeUpgradeable,
  ERC1967UpgradeUpgradeableInterface,
} from "../ERC1967UpgradeUpgradeable";

const _abi = [
  "event AdminChanged(address,address)",
  "event BeaconUpgraded(address indexed)",
  "event Initialized(uint8)",
  "event Upgraded(address indexed)",
] as const;

export class ERC1967UpgradeUpgradeable__factory {
  static readonly abi = _abi;
  static createInterface(): ERC1967UpgradeUpgradeableInterface {
    return new Interface(_abi) as ERC1967UpgradeUpgradeableInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): ERC1967UpgradeUpgradeable {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as ERC1967UpgradeUpgradeable;
  }
}
