/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type { ICashman, ICashmanInterface } from "../ICashman";

const _abi = [
  "event Approval(address indexed,address indexed,uint256)",
  "event Transfer(address indexed,address indexed,uint256)",
  "function allowance(address,address) view returns (uint256)",
  "function approve(address,uint256) returns (bool)",
  "function balanceOf(address) view returns (uint256)",
  "function buyIn(uint256,address) payable returns (uint256)",
  "function cashOut(uint256,address) returns (uint256, uint256)",
  "function totalSupply() view returns (uint256)",
  "function transfer(address,uint256) returns (bool)",
  "function transferFrom(address,address,uint256) returns (bool)",
] as const;

export class ICashman__factory {
  static readonly abi = _abi;
  static createInterface(): ICashmanInterface {
    return new Interface(_abi) as ICashmanInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): ICashman {
    return new Contract(address, _abi, runner) as unknown as ICashman;
  }
}
