/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type { IOneTimeDraw, IOneTimeDrawInterface } from "../IOneTimeDraw";

const _abi = [
  "event PlayerDrewCards(address indexed,uint256[])",
  "function drawCardsNSubmitRevealTokens(address,uint256[],uint256[],bytes[],bytes[])",
  "function foldCards(address,uint256[],bytes[],bytes[])",
  "function showHand(address,uint256[],bytes[],bytes[])",
] as const;

export class IOneTimeDraw__factory {
  static readonly abi = _abi;
  static createInterface(): IOneTimeDrawInterface {
    return new Interface(_abi) as IOneTimeDrawInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IOneTimeDraw {
    return new Contract(address, _abi, runner) as unknown as IOneTimeDraw;
  }
}
