/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  ITexasHoldemHelper,
  ITexasHoldemHelperInterface,
} from "../ITexasHoldemHelper";

const _abi = [
  "function bestHand(tuple(uint8,uint8)[],tuple(uint8,uint8)[]) pure returns (uint8, uint64)",
  "function computeNextPlayer(tuple(uint8,uint8,uint32,uint256,uint256,uint16,uint16,uint16,uint16,uint16,uint8),tuple(uint32,uint32,uint32,uint32),uint8,uint8,uint32) view returns (tuple(uint8,uint8,uint32,uint256,uint256,uint16,uint16,uint16,uint16,uint16,uint8))",
  "function computePotWinners(tuple(uint8,uint64,uint256,uint8,uint16,uint16)[],uint8,tuple(uint8,uint8)[],tuple(uint8,uint8)[],uint256[],uint256[],uint16) view returns (tuple(uint8,uint64,uint256,uint8,uint16,uint16)[])",
  "function computePots(uint256[],uint256[],uint16) view returns (tuple(uint256,uint8[])[])",
  "function computeSortedAllinAmounts(uint256[],uint256) pure returns (uint256[])",
  "function createSignMessage(string,uint64) view returns (string)",
  "function getHandRanking(tuple(uint8,uint8)[5]) pure returns (uint8, uint64)",
  "function parseSigner(bytes,string) pure returns (address)",
] as const;

export class ITexasHoldemHelper__factory {
  static readonly abi = _abi;
  static createInterface(): ITexasHoldemHelperInterface {
    return new Interface(_abi) as ITexasHoldemHelperInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): ITexasHoldemHelper {
    return new Contract(address, _abi, runner) as unknown as ITexasHoldemHelper;
  }
}
