/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type { Ownable, OwnableInterface } from "../Ownable";

const _abi = [
  "event OwnershipTransferred(address indexed,address indexed)",
  "function owner() view returns (address)",
  "function renounceOwnership()",
  "function transferOwnership(address)",
] as const;

export class Ownable__factory {
  static readonly abi = _abi;
  static createInterface(): OwnableInterface {
    return new Interface(_abi) as OwnableInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): Ownable {
    return new Contract(address, _abi, runner) as unknown as Ownable;
  }
}
