/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  OwnableUpgradeable,
  OwnableUpgradeableInterface,
} from "../OwnableUpgradeable";

const _abi = [
  "event Initialized(uint8)",
  "event OwnershipTransferred(address indexed,address indexed)",
  "function owner() view returns (address)",
  "function renounceOwnership()",
  "function transferOwnership(address)",
] as const;

export class OwnableUpgradeable__factory {
  static readonly abi = _abi;
  static createInterface(): OwnableUpgradeableInterface {
    return new Interface(_abi) as OwnableUpgradeableInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): OwnableUpgradeable {
    return new Contract(address, _abi, runner) as unknown as OwnableUpgradeable;
  }
}
