/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type { Dev, DevInterface } from "../Dev";

const _abi = [
  "function RATE(uint256) view returns (uint256)",
  "function buyout(uint256,uint256) view returns (uint256)",
  "function sum(uint8,uint8) pure returns (uint8)",
] as const;

export class Dev__factory {
  static readonly abi = _abi;
  static createInterface(): DevInterface {
    return new utils.Interface(_abi) as DevInterface;
  }
  static connect(address: string, signerOrProvider: Signer | Provider): Dev {
    return new Contract(address, _abi, signerOrProvider) as Dev;
  }
}
