/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type { IMentalPoker, IMentalPokerInterface } from "../IMentalPoker";

const _abi = [
  "function computeAggregateKey(bytes[]) pure returns (bytes)",
  "function mask(bytes,bytes,bytes) pure returns (bytes)",
  "function reveal(bytes[],bytes) pure returns (bytes)",
  "function test(bytes,bytes[]) view returns (bytes)",
  "function verifyKeyOwnership(bytes,bytes,bytes,bytes) pure returns (bool)",
  "function verifyReveal(bytes,bytes,bytes,bytes,bytes) pure returns (bool)",
  "function verifyShuffle(bytes,bytes,bytes[],bytes[],bytes) pure returns (bool)",
] as const;

export class IMentalPoker__factory {
  static readonly abi = _abi;
  static createInterface(): IMentalPokerInterface {
    return new utils.Interface(_abi) as IMentalPokerInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IMentalPoker {
    return new Contract(address, _abi, signerOrProvider) as IMentalPoker;
  }
}
