/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type { IOneTimeDraw, IOneTimeDrawInterface } from "../IOneTimeDraw";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "player",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256[]",
        name: "cards",
        type: "uint256[]",
      },
    ],
    name: "PlayerDrewCards",
    type: "event",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_player",
        type: "address",
      },
      {
        internalType: "uint256[]",
        name: "_myIndexes",
        type: "uint256[]",
      },
      {
        internalType: "uint256[]",
        name: "_othersIndexes",
        type: "uint256[]",
      },
      {
        internalType: "bytes[]",
        name: "_revealTokens",
        type: "bytes[]",
      },
      {
        internalType: "bytes[]",
        name: "_revealProofs",
        type: "bytes[]",
      },
    ],
    name: "drawCardsNSubmitRevealTokens",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_player",
        type: "address",
      },
      {
        internalType: "uint256[]",
        name: "_unrevealedIndexes",
        type: "uint256[]",
      },
      {
        internalType: "bytes[]",
        name: "_revealTokens",
        type: "bytes[]",
      },
      {
        internalType: "bytes[]",
        name: "_revealProofs",
        type: "bytes[]",
      },
    ],
    name: "foldCards",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_player",
        type: "address",
      },
      {
        internalType: "uint256[]",
        name: "_cardIndexes",
        type: "uint256[]",
      },
      {
        internalType: "bytes[]",
        name: "_revealTokens",
        type: "bytes[]",
      },
      {
        internalType: "bytes[]",
        name: "_revealProofs",
        type: "bytes[]",
      },
    ],
    name: "showHand",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IOneTimeDraw__factory {
  static readonly abi = _abi;
  static createInterface(): IOneTimeDrawInterface {
    return new utils.Interface(_abi) as IOneTimeDrawInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IOneTimeDraw {
    return new Contract(address, _abi, signerOrProvider) as IOneTimeDraw;
  }
}
