/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type { IPokerTable, IPokerTableInterface } from "../IPokerTable";

const _abi = [
  "function activePlayerCounts() view returns (uint8)",
  "function info() view returns (tuple(uint32,string,address,uint8,uint8,uint8,uint256))",
  "function isPlaying() view returns (bool)",
  "function newTable(tuple(address,string)[]) payable",
  "function position(uint8) view returns (tuple(uint8,tuple(address,string),uint256,uint256,uint32))",
  "function totalPots() view returns (uint256)",
] as const;

export class IPokerTable__factory {
  static readonly abi = _abi;
  static createInterface(): IPokerTableInterface {
    return new utils.Interface(_abi) as IPokerTableInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IPokerTable {
    return new Contract(address, _abi, signerOrProvider) as IPokerTable;
  }
}
