/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type { MuAddress, MuAddressInterface } from "../MuAddress";

const _abi = [
  {
    inputs: [],
    name: "AddressError",
    type: "error",
  },
  {
    inputs: [],
    name: "AddressInsuffcientBalance",
    type: "error",
  },
  {
    inputs: [],
    name: "AddressNotContract",
    type: "error",
  },
] as const;

export class MuAddress__factory {
  static readonly abi = _abi;
  static createInterface(): MuAddressInterface {
    return new utils.Interface(_abi) as MuAddressInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): MuAddress {
    return new Contract(address, _abi, signerOrProvider) as MuAddress;
  }
}
