/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  MuInitializable,
  MuInitializableInterface,
} from "../MuInitializable";

const _abi = [
  {
    inputs: [],
    name: "AlreadyInitialized",
    type: "error",
  },
  {
    inputs: [],
    name: "Initializing",
    type: "error",
  },
  {
    inputs: [],
    name: "NotInitializing",
    type: "error",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "uint8",
        name: "version",
        type: "uint8",
      },
    ],
    name: "Initialized",
    type: "event",
  },
] as const;

export class MuInitializable__factory {
  static readonly abi = _abi;
  static createInterface(): MuInitializableInterface {
    return new utils.Interface(_abi) as MuInitializableInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): MuInitializable {
    return new Contract(address, _abi, signerOrProvider) as MuInitializable;
  }
}
