/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type { MuOwnable, MuOwnableInterface } from "../MuOwnable";

const _abi = [
  {
    inputs: [],
    name: "OwnableInvalid",
    type: "error",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "previousOwner",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "newOwner",
        type: "address",
      },
    ],
    name: "OwnershipTransferred",
    type: "event",
  },
  {
    inputs: [],
    name: "owner",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "renounceOwnership",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "newOwner",
        type: "address",
      },
    ],
    name: "transferOwnership",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class MuOwnable__factory {
  static readonly abi = _abi;
  static createInterface(): MuOwnableInterface {
    return new utils.Interface(_abi) as MuOwnableInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): MuOwnable {
    return new Contract(address, _abi, signerOrProvider) as MuOwnable;
  }
}
