/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  TexasHoldemPeriphery,
  TexasHoldemPeripheryInterface,
} from "../TexasHoldemPeriphery";

const _abi = [
  "event AdminChanged(address,address)",
  "event BeaconUpgraded(address indexed)",
  "event Initialized(uint8)",
  "event OwnershipTransferred(address indexed,address indexed)",
  "event Upgraded(address indexed)",
  "function _tableStatus(address,bytes) view returns (tuple(address,string,uint8,tuple(uint8,uint8)[],tuple(uint8,address,string,uint8,tuple(uint8,uint8)[],uint256,uint256)[],tuple(uint256,uint8[],uint8),tuple(uint256,uint8[],uint8)[],uint256,uint256,uint8,uint32,uint32,uint32))",
  "function initialize(address)",
  "function lobby() view returns (address)",
  "function lobbyTables() view returns (tuple(uint32,address,uint8,uint8,uint8,tuple(address,string,bytes)[],tuple(uint8,uint8,bytes,bytes[]),tuple(uint8,address[],uint32))[])",
  "function owner() view returns (address)",
  "function proxiableUUID() view returns (bytes32)",
  "function renounceOwnership()",
  "function tableByAddress(address,bytes) view returns (tuple(address,string,uint8,tuple(uint8,uint8)[],tuple(uint8,address,string,uint8,tuple(uint8,uint8)[],uint256,uint256)[],tuple(uint256,uint8[],uint8),tuple(uint256,uint8[],uint8)[],uint256,uint256,uint8,uint32,uint32,uint32))",
  "function tableByIndex(uint8,bytes) view returns (tuple(address,string,uint8,tuple(uint8,uint8)[],tuple(uint8,address,string,uint8,tuple(uint8,uint8)[],uint256,uint256)[],tuple(uint256,uint8[],uint8),tuple(uint256,uint8[],uint8)[],uint256,uint256,uint8,uint32,uint32,uint32))",
  "function transferOwnership(address)",
  "function upgradeTo(address)",
  "function upgradeToAndCall(address,bytes) payable",
] as const;

export class TexasHoldemPeriphery__factory {
  static readonly abi = _abi;
  static createInterface(): TexasHoldemPeripheryInterface {
    return new utils.Interface(_abi) as TexasHoldemPeripheryInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): TexasHoldemPeriphery {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as TexasHoldemPeriphery;
  }
}
