/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  UUPSUpgradeable,
  UUPSUpgradeableInterface,
} from "../UUPSUpgradeable";

const _abi = [
  "event AdminChanged(address,address)",
  "event BeaconUpgraded(address indexed)",
  "event Initialized(uint8)",
  "event Upgraded(address indexed)",
  "function proxiableUUID() view returns (bytes32)",
  "function upgradeTo(address)",
  "function upgradeToAndCall(address,bytes) payable",
] as const;

export class UUPSUpgradeable__factory {
  static readonly abi = _abi;
  static createInterface(): UUPSUpgradeableInterface {
    return new utils.Interface(_abi) as UUPSUpgradeableInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): UUPSUpgradeable {
    return new Contract(address, _abi, signerOrProvider) as UUPSUpgradeable;
  }
}
