/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export declare namespace IPokerTable {
  export type PokerCardStruct = { suit: BigNumberish; rank: BigNumberish };

  export type PokerCardStructOutput = [suit: bigint, rank: bigint] & {
    suit: bigint;
    rank: bigint;
  };

  export type PlayerStruct = { wallet: AddressLike; name: string };

  export type PlayerStructOutput = [wallet: string, name: string] & {
    wallet: string;
    name: string;
  };

  export type InfoStruct = {
    subject: string;
    lobby: AddressLike;
    gameType: BigNumberish;
    status: BigNumberish;
    seats: BigNumberish;
    initialBuyin: BigNumberish;
  };

  export type InfoStructOutput = [
    subject: string,
    lobby: string,
    gameType: bigint,
    status: bigint,
    seats: bigint,
    initialBuyin: bigint
  ] & {
    subject: string;
    lobby: string;
    gameType: bigint;
    status: bigint;
    seats: bigint;
    initialBuyin: bigint;
  };

  export type PositionStruct = {
    pid: BigNumberish;
    player: IPokerTable.PlayerStruct;
    wins: BigNumberish;
    draws: BigNumberish;
    bets: BigNumberish;
    chips: BigNumberish;
    pendingBuyin: BigNumberish;
  };

  export type PositionStructOutput = [
    pid: bigint,
    player: IPokerTable.PlayerStructOutput,
    wins: bigint,
    draws: bigint,
    bets: bigint,
    chips: bigint,
    pendingBuyin: bigint
  ] & {
    pid: bigint;
    player: IPokerTable.PlayerStructOutput;
    wins: bigint;
    draws: bigint;
    bets: bigint;
    chips: bigint;
    pendingBuyin: bigint;
  };
}

export declare namespace ITexasHoldemTable {
  export type TexasHoldemPositionStruct = {
    pid: BigNumberish;
    player: IPokerTable.PlayerStruct;
    status: BigNumberish;
    bets: BigNumberish;
    chips: BigNumberish;
    pendingBuyin: BigNumberish;
    holeCards: IPokerTable.PokerCardStruct[];
    wins: BigNumberish;
    draws: BigNumberish;
  };

  export type TexasHoldemPositionStructOutput = [
    pid: bigint,
    player: IPokerTable.PlayerStructOutput,
    status: bigint,
    bets: bigint,
    chips: bigint,
    pendingBuyin: bigint,
    holeCards: IPokerTable.PokerCardStructOutput[],
    wins: bigint,
    draws: bigint
  ] & {
    pid: bigint;
    player: IPokerTable.PlayerStructOutput;
    status: bigint;
    bets: bigint;
    chips: bigint;
    pendingBuyin: bigint;
    holeCards: IPokerTable.PokerCardStructOutput[];
    wins: bigint;
    draws: bigint;
  };

  export type TexasHoldemGameStruct = {
    id: BigNumberish;
    subject: string;
    stage: BigNumberish;
    communityCards: IPokerTable.PokerCardStruct[];
    positions: ITexasHoldemTable.TexasHoldemPositionStruct[];
    pot: BigNumberish;
    minRaise: BigNumberish;
    betAmount: BigNumberish;
    actingPosition: BigNumberish;
    actingTimeout: BigNumberish;
  };

  export type TexasHoldemGameStructOutput = [
    id: bigint,
    subject: string,
    stage: bigint,
    communityCards: IPokerTable.PokerCardStructOutput[],
    positions: ITexasHoldemTable.TexasHoldemPositionStructOutput[],
    pot: bigint,
    minRaise: bigint,
    betAmount: bigint,
    actingPosition: bigint,
    actingTimeout: bigint
  ] & {
    id: bigint;
    subject: string;
    stage: bigint;
    communityCards: IPokerTable.PokerCardStructOutput[];
    positions: ITexasHoldemTable.TexasHoldemPositionStructOutput[];
    pot: bigint;
    minRaise: bigint;
    betAmount: bigint;
    actingPosition: bigint;
    actingTimeout: bigint;
  };
}

export interface DemoTableInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "TABLE_TIMEOUT"
      | "allinBets"
      | "allowance"
      | "approve"
      | "balanceOf"
      | "bets"
      | "callBets"
      | "checkBets"
      | "cutCards"
      | "decimals"
      | "decreaseAllowance"
      | "ff"
      | "foldBets"
      | "forceNewGame"
      | "game"
      | "getAllPositions"
      | "getBigBlind"
      | "getGamePlayerCounts"
      | "getPositionHandRanking"
      | "getSmallBlind"
      | "highestBet"
      | "inTable"
      | "increaseAllowance"
      | "info"
      | "isPlaying"
      | "name"
      | "newTable"
      | "owner"
      | "playerCounts"
      | "positions"
      | "pot"
      | "raiseBets"
      | "renounceOwnership"
      | "setup"
      | "symbol"
      | "totalSupply"
      | "transfer"
      | "transferFrom"
      | "transferOwnership"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "Approval"
      | "Initialized"
      | "OwnershipTransferred"
      | "Transfer"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "TABLE_TIMEOUT",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "allinBets", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "allowance",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "approve",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "balanceOf",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "bets", values: [AddressLike]): string;
  encodeFunctionData(functionFragment: "callBets", values?: undefined): string;
  encodeFunctionData(functionFragment: "checkBets", values?: undefined): string;
  encodeFunctionData(functionFragment: "cutCards", values?: undefined): string;
  encodeFunctionData(functionFragment: "decimals", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "decreaseAllowance",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "ff", values?: undefined): string;
  encodeFunctionData(functionFragment: "foldBets", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "forceNewGame",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "game", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "getAllPositions",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getBigBlind",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getGamePlayerCounts",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getPositionHandRanking",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getSmallBlind",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "highestBet",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "inTable",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "increaseAllowance",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "info", values?: undefined): string;
  encodeFunctionData(functionFragment: "isPlaying", values?: undefined): string;
  encodeFunctionData(functionFragment: "name", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "newTable",
    values: [IPokerTable.PlayerStruct[]]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "playerCounts",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "positions", values?: undefined): string;
  encodeFunctionData(functionFragment: "pot", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "raiseBets",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setup",
    values: [
      string,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      AddressLike,
      BytesLike[]
    ]
  ): string;
  encodeFunctionData(functionFragment: "symbol", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "totalSupply",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transfer",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "transferFrom",
    values: [AddressLike, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "TABLE_TIMEOUT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "allinBets", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "allowance", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "approve", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "balanceOf", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "bets", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "callBets", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "checkBets", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "cutCards", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "decimals", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "decreaseAllowance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "ff", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "foldBets", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "forceNewGame",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "game", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getAllPositions",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getBigBlind",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getGamePlayerCounts",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPositionHandRanking",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getSmallBlind",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "highestBet", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "inTable", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "increaseAllowance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "info", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "isPlaying", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "name", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "newTable", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "playerCounts",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "positions", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "pot", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "raiseBets", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setup", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "symbol", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "totalSupply",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "transfer", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferFrom",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
}

export namespace ApprovalEvent {
  export type InputTuple = [
    owner: AddressLike,
    spender: AddressLike,
    value: BigNumberish
  ];
  export type OutputTuple = [owner: string, spender: string, value: bigint];
  export interface OutputObject {
    owner: string;
    spender: string;
    value: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace InitializedEvent {
  export type InputTuple = [version: BigNumberish];
  export type OutputTuple = [version: bigint];
  export interface OutputObject {
    version: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TransferEvent {
  export type InputTuple = [
    from: AddressLike,
    to: AddressLike,
    value: BigNumberish
  ];
  export type OutputTuple = [from: string, to: string, value: bigint];
  export interface OutputObject {
    from: string;
    to: string;
    value: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface DemoTable extends BaseContract {
  connect(runner?: ContractRunner | null): DemoTable;
  waitForDeployment(): Promise<this>;

  interface: DemoTableInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  TABLE_TIMEOUT: TypedContractMethod<[], [bigint], "view">;

  allinBets: TypedContractMethod<[], [void], "nonpayable">;

  allowance: TypedContractMethod<
    [owner: AddressLike, spender: AddressLike],
    [bigint],
    "view"
  >;

  approve: TypedContractMethod<
    [spender: AddressLike, amount: BigNumberish],
    [boolean],
    "nonpayable"
  >;

  balanceOf: TypedContractMethod<[account: AddressLike], [bigint], "view">;

  bets: TypedContractMethod<[player: AddressLike], [bigint], "view">;

  callBets: TypedContractMethod<[], [void], "nonpayable">;

  checkBets: TypedContractMethod<[], [void], "nonpayable">;

  cutCards: TypedContractMethod<[], [void], "nonpayable">;

  decimals: TypedContractMethod<[], [bigint], "view">;

  decreaseAllowance: TypedContractMethod<
    [spender: AddressLike, subtractedValue: BigNumberish],
    [boolean],
    "nonpayable"
  >;

  ff: TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint] & {
        stage: bigint;
        position: bigint;
        timeout: bigint;
      }
    ],
    "view"
  >;

  foldBets: TypedContractMethod<[], [void], "nonpayable">;

  forceNewGame: TypedContractMethod<[], [void], "nonpayable">;

  game: TypedContractMethod<
    [signature: BytesLike],
    [ITexasHoldemTable.TexasHoldemGameStructOutput],
    "view"
  >;

  getAllPositions: TypedContractMethod<
    [viewer: AddressLike],
    [ITexasHoldemTable.TexasHoldemPositionStructOutput[]],
    "view"
  >;

  getBigBlind: TypedContractMethod<
    [],
    [[string, bigint] & { player: string; amount: bigint }],
    "view"
  >;

  getGamePlayerCounts: TypedContractMethod<
    [gameId: BigNumberish],
    [bigint],
    "view"
  >;

  getPositionHandRanking: TypedContractMethod<
    [pos: BigNumberish],
    [[bigint, bigint] & { ranking: bigint; kickers: bigint }],
    "view"
  >;

  getSmallBlind: TypedContractMethod<
    [],
    [[string, bigint] & { player: string; amount: bigint }],
    "view"
  >;

  highestBet: TypedContractMethod<[], [bigint], "view">;

  inTable: TypedContractMethod<[player: AddressLike], [boolean], "view">;

  increaseAllowance: TypedContractMethod<
    [spender: AddressLike, addedValue: BigNumberish],
    [boolean],
    "nonpayable"
  >;

  info: TypedContractMethod<[], [IPokerTable.InfoStructOutput], "view">;

  isPlaying: TypedContractMethod<[], [boolean], "view">;

  name: TypedContractMethod<[], [string], "view">;

  newTable: TypedContractMethod<
    [players: IPokerTable.PlayerStruct[]],
    [void],
    "payable"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  playerCounts: TypedContractMethod<[], [bigint], "view">;

  positions: TypedContractMethod<
    [],
    [IPokerTable.PositionStructOutput[]],
    "view"
  >;

  pot: TypedContractMethod<[], [bigint], "view">;

  raiseBets: TypedContractMethod<
    [totalAmount: BigNumberish],
    [void],
    "nonpayable"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  setup: TypedContractMethod<
    [
      subject: string,
      seats: BigNumberish,
      bbAmount: BigNumberish,
      sbAmount: BigNumberish,
      anteAmount: BigNumberish,
      initialBuyin: BigNumberish,
      helper: AddressLike,
      cardFaces: BytesLike[]
    ],
    [void],
    "nonpayable"
  >;

  symbol: TypedContractMethod<[], [string], "view">;

  totalSupply: TypedContractMethod<[], [bigint], "view">;

  transfer: TypedContractMethod<
    [to: AddressLike, amount: BigNumberish],
    [boolean],
    "nonpayable"
  >;

  transferFrom: TypedContractMethod<
    [from: AddressLike, to: AddressLike, amount: BigNumberish],
    [boolean],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "TABLE_TIMEOUT"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "allinBets"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "allowance"
  ): TypedContractMethod<
    [owner: AddressLike, spender: AddressLike],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "approve"
  ): TypedContractMethod<
    [spender: AddressLike, amount: BigNumberish],
    [boolean],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "balanceOf"
  ): TypedContractMethod<[account: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "bets"
  ): TypedContractMethod<[player: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "callBets"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "checkBets"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "cutCards"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "decimals"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "decreaseAllowance"
  ): TypedContractMethod<
    [spender: AddressLike, subtractedValue: BigNumberish],
    [boolean],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "ff"
  ): TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint] & {
        stage: bigint;
        position: bigint;
        timeout: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "foldBets"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "forceNewGame"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "game"
  ): TypedContractMethod<
    [signature: BytesLike],
    [ITexasHoldemTable.TexasHoldemGameStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getAllPositions"
  ): TypedContractMethod<
    [viewer: AddressLike],
    [ITexasHoldemTable.TexasHoldemPositionStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getBigBlind"
  ): TypedContractMethod<
    [],
    [[string, bigint] & { player: string; amount: bigint }],
    "view"
  >;
  getFunction(
    nameOrSignature: "getGamePlayerCounts"
  ): TypedContractMethod<[gameId: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "getPositionHandRanking"
  ): TypedContractMethod<
    [pos: BigNumberish],
    [[bigint, bigint] & { ranking: bigint; kickers: bigint }],
    "view"
  >;
  getFunction(
    nameOrSignature: "getSmallBlind"
  ): TypedContractMethod<
    [],
    [[string, bigint] & { player: string; amount: bigint }],
    "view"
  >;
  getFunction(
    nameOrSignature: "highestBet"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "inTable"
  ): TypedContractMethod<[player: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "increaseAllowance"
  ): TypedContractMethod<
    [spender: AddressLike, addedValue: BigNumberish],
    [boolean],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "info"
  ): TypedContractMethod<[], [IPokerTable.InfoStructOutput], "view">;
  getFunction(
    nameOrSignature: "isPlaying"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "name"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "newTable"
  ): TypedContractMethod<
    [players: IPokerTable.PlayerStruct[]],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "playerCounts"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "positions"
  ): TypedContractMethod<[], [IPokerTable.PositionStructOutput[]], "view">;
  getFunction(
    nameOrSignature: "pot"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "raiseBets"
  ): TypedContractMethod<[totalAmount: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setup"
  ): TypedContractMethod<
    [
      subject: string,
      seats: BigNumberish,
      bbAmount: BigNumberish,
      sbAmount: BigNumberish,
      anteAmount: BigNumberish,
      initialBuyin: BigNumberish,
      helper: AddressLike,
      cardFaces: BytesLike[]
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "symbol"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "totalSupply"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "transfer"
  ): TypedContractMethod<
    [to: AddressLike, amount: BigNumberish],
    [boolean],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "transferFrom"
  ): TypedContractMethod<
    [from: AddressLike, to: AddressLike, amount: BigNumberish],
    [boolean],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "Approval"
  ): TypedContractEvent<
    ApprovalEvent.InputTuple,
    ApprovalEvent.OutputTuple,
    ApprovalEvent.OutputObject
  >;
  getEvent(
    key: "Initialized"
  ): TypedContractEvent<
    InitializedEvent.InputTuple,
    InitializedEvent.OutputTuple,
    InitializedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "Transfer"
  ): TypedContractEvent<
    TransferEvent.InputTuple,
    TransferEvent.OutputTuple,
    TransferEvent.OutputObject
  >;

  filters: {
    "Approval(address,address,uint256)": TypedContractEvent<
      ApprovalEvent.InputTuple,
      ApprovalEvent.OutputTuple,
      ApprovalEvent.OutputObject
    >;
    Approval: TypedContractEvent<
      ApprovalEvent.InputTuple,
      ApprovalEvent.OutputTuple,
      ApprovalEvent.OutputObject
    >;

    "Initialized(uint8)": TypedContractEvent<
      InitializedEvent.InputTuple,
      InitializedEvent.OutputTuple,
      InitializedEvent.OutputObject
    >;
    Initialized: TypedContractEvent<
      InitializedEvent.InputTuple,
      InitializedEvent.OutputTuple,
      InitializedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "Transfer(address,address,uint256)": TypedContractEvent<
      TransferEvent.InputTuple,
      TransferEvent.OutputTuple,
      TransferEvent.OutputObject
    >;
    Transfer: TypedContractEvent<
      TransferEvent.InputTuple,
      TransferEvent.OutputTuple,
      TransferEvent.OutputObject
    >;
  };
}
