/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "./common";

export declare namespace IPokerTable {
  export type PokerCardStruct = { suit: BigNumberish; rank: BigNumberish };

  export type PokerCardStructOutput = [suit: bigint, rank: bigint] & {
    suit: bigint;
    rank: bigint;
  };

  export type PlayerStruct = { wallet: AddressLike; name: string };

  export type PlayerStructOutput = [wallet: string, name: string] & {
    wallet: string;
    name: string;
  };

  export type InfoStruct = {
    subject: string;
    lobby: AddressLike;
    gameType: BigNumberish;
    status: BigNumberish;
    seats: BigNumberish;
    initialBuyin: BigNumberish;
  };

  export type InfoStructOutput = [
    subject: string,
    lobby: string,
    gameType: bigint,
    status: bigint,
    seats: bigint,
    initialBuyin: bigint
  ] & {
    subject: string;
    lobby: string;
    gameType: bigint;
    status: bigint;
    seats: bigint;
    initialBuyin: bigint;
  };

  export type PositionStruct = {
    pid: BigNumberish;
    player: IPokerTable.PlayerStruct;
    wins: BigNumberish;
    draws: BigNumberish;
    bets: BigNumberish;
    chips: BigNumberish;
    pendingBuyin: BigNumberish;
  };

  export type PositionStructOutput = [
    pid: bigint,
    player: IPokerTable.PlayerStructOutput,
    wins: bigint,
    draws: bigint,
    bets: bigint,
    chips: bigint,
    pendingBuyin: bigint
  ] & {
    pid: bigint;
    player: IPokerTable.PlayerStructOutput;
    wins: bigint;
    draws: bigint;
    bets: bigint;
    chips: bigint;
    pendingBuyin: bigint;
  };
}

export declare namespace ITexasHoldemTable {
  export type TexasHoldemPositionStruct = {
    pid: BigNumberish;
    player: IPokerTable.PlayerStruct;
    status: BigNumberish;
    bets: BigNumberish;
    chips: BigNumberish;
    pendingBuyin: BigNumberish;
    holeCards: IPokerTable.PokerCardStruct[];
    wins: BigNumberish;
    draws: BigNumberish;
  };

  export type TexasHoldemPositionStructOutput = [
    pid: bigint,
    player: IPokerTable.PlayerStructOutput,
    status: bigint,
    bets: bigint,
    chips: bigint,
    pendingBuyin: bigint,
    holeCards: IPokerTable.PokerCardStructOutput[],
    wins: bigint,
    draws: bigint
  ] & {
    pid: bigint;
    player: IPokerTable.PlayerStructOutput;
    status: bigint;
    bets: bigint;
    chips: bigint;
    pendingBuyin: bigint;
    holeCards: IPokerTable.PokerCardStructOutput[];
    wins: bigint;
    draws: bigint;
  };

  export type TexasHoldemGameStruct = {
    id: BigNumberish;
    subject: string;
    stage: BigNumberish;
    communityCards: IPokerTable.PokerCardStruct[];
    positions: ITexasHoldemTable.TexasHoldemPositionStruct[];
    pot: BigNumberish;
    minRaise: BigNumberish;
    betAmount: BigNumberish;
    actingPosition: BigNumberish;
    actingTimeout: BigNumberish;
  };

  export type TexasHoldemGameStructOutput = [
    id: bigint,
    subject: string,
    stage: bigint,
    communityCards: IPokerTable.PokerCardStructOutput[],
    positions: ITexasHoldemTable.TexasHoldemPositionStructOutput[],
    pot: bigint,
    minRaise: bigint,
    betAmount: bigint,
    actingPosition: bigint,
    actingTimeout: bigint
  ] & {
    id: bigint;
    subject: string;
    stage: bigint;
    communityCards: IPokerTable.PokerCardStructOutput[];
    positions: ITexasHoldemTable.TexasHoldemPositionStructOutput[];
    pot: bigint;
    minRaise: bigint;
    betAmount: bigint;
    actingPosition: bigint;
    actingTimeout: bigint;
  };
}

export interface ITexasHoldemTableInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "game"
      | "info"
      | "isPlaying"
      | "newTable"
      | "positions"
      | "setup"
  ): FunctionFragment;

  encodeFunctionData(functionFragment: "game", values: [BytesLike]): string;
  encodeFunctionData(functionFragment: "info", values?: undefined): string;
  encodeFunctionData(functionFragment: "isPlaying", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "newTable",
    values: [IPokerTable.PlayerStruct[]]
  ): string;
  encodeFunctionData(functionFragment: "positions", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "setup",
    values: [
      string,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      AddressLike,
      BytesLike[]
    ]
  ): string;

  decodeFunctionResult(functionFragment: "game", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "info", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "isPlaying", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "newTable", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "positions", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "setup", data: BytesLike): Result;
}

export interface ITexasHoldemTable extends BaseContract {
  connect(runner?: ContractRunner | null): ITexasHoldemTable;
  waitForDeployment(): Promise<this>;

  interface: ITexasHoldemTableInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  game: TypedContractMethod<
    [signature: BytesLike],
    [ITexasHoldemTable.TexasHoldemGameStructOutput],
    "view"
  >;

  info: TypedContractMethod<[], [IPokerTable.InfoStructOutput], "view">;

  isPlaying: TypedContractMethod<[], [boolean], "view">;

  newTable: TypedContractMethod<
    [players: IPokerTable.PlayerStruct[]],
    [void],
    "payable"
  >;

  positions: TypedContractMethod<
    [],
    [IPokerTable.PositionStructOutput[]],
    "view"
  >;

  setup: TypedContractMethod<
    [
      subject: string,
      seats: BigNumberish,
      bbAmount: BigNumberish,
      sbAmount: BigNumberish,
      anteAmount: BigNumberish,
      initialBuyin: BigNumberish,
      helper: AddressLike,
      cardIds: BytesLike[]
    ],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "game"
  ): TypedContractMethod<
    [signature: BytesLike],
    [ITexasHoldemTable.TexasHoldemGameStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "info"
  ): TypedContractMethod<[], [IPokerTable.InfoStructOutput], "view">;
  getFunction(
    nameOrSignature: "isPlaying"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "newTable"
  ): TypedContractMethod<
    [players: IPokerTable.PlayerStruct[]],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "positions"
  ): TypedContractMethod<[], [IPokerTable.PositionStructOutput[]], "view">;
  getFunction(
    nameOrSignature: "setup"
  ): TypedContractMethod<
    [
      subject: string,
      seats: BigNumberish,
      bbAmount: BigNumberish,
      sbAmount: BigNumberish,
      anteAmount: BigNumberish,
      initialBuyin: BigNumberish,
      helper: AddressLike,
      cardIds: BytesLike[]
    ],
    [void],
    "nonpayable"
  >;

  filters: {};
}
